export const CREATE_COURSE = "CREATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSE_SUCCESS";
export const LOAD_STUDENT_SUCCESS = "LOAD_STUDENT_SUCCESS";
export const FETCH_STUDENT_SUCCESS = "FETCH_STUDENT_SUCCESS";
export const REGISTER_COURSES = "REGISTER_COURSES";
export const LOAD_AVAILABLE_COURSES = "LOAD_AVAILABLE_COURSES";
